### ISSUE TITLE
[User feedback] Saving sync rule from manual sync doesnt open in editino mode

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#47]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/sync-rules/events

but

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1583228994131872072.png )

**Comment by adrianq** [comment]
@ifoche we are saving the rule and then sending the user to the first step in the wizard. Is this the expected behaviour? the alternative is to send the user to the first step without saving the rule in advance, i.e. if the user doesn't go to the last step and press save the sync rule will be lost...

**Comment by ifoche** [comment]
Sorry @adrianq I didn't see this comment earlier. Sure, I think that behaviour is perfect. Thanks!

**Comment by adrianq** [comment]
Done in https://github.com/EyeSeeTea/metadata-synchronization/pull/407/commits/e29b0afb6aa93361c692bd268860663351817130
